version: '3'

services:
  db:
    image: "postgres:13.1-alpine"
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dps
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
  app:
    build: .
    ports:
      - "8080:8080"
    container_name: app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dps
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
